### ISSUE TITLE
"nay" interpreted as "yay" in ConwaysGameOfLife.py

### ISSUE THREAD

**Issue by lkolbly** [bobpaw/adv-coding#2]
> $ python ConwaysGameOfLife.py
> Do you want to load a premade object? **nay**
> What do you want to preload? ...

"nay" does not mean "yes".

@ToxicOverload

**Comment by bobpaw** [comment]
Closed by commit a78d6c4.

**Comment by lkolbly** [comment]
The same issue is present for importing too, I believe.
